//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantEx
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Designation { get; set; }
        public int YearOfEx { get; set; }
        public int AppId { get; set; }
    
        public virtual Applicant Applicant { get; set; }
    }
}
