//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.Web.UI.HtmlControls;

    public partial class Applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant()
        {
            this.ApplicantExes = new List<ApplicantEx>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }
        public string PicPath { get; set; }
        public bool IsAvailable { get; set; }
        public int TotalEx { get; set; }
        [NotMapped]
        public HttpPostedFileBase Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<ApplicantEx> ApplicantExes { get; set; }
    }
}
